### ISSUE TITLE
Auto-scroll to active tab doesn't always work

### ISSUE THREAD

**Issue by chaoscreater** [RabbitPair/colorful_sidepanel_tabs_extension#73]
Hi there,

If I search for a tab (e.g. Google.com), then click on the tab in the result, it doesn't auto-scroll to the tab after I remove the search. If I do CTRL+TAB to switch to the next tab and then switch it back to the original tab (Google.com), auto-scroll to tab still doesn't work. I think the issue is that if the tab that you searched for is in a tab group, when you remove the search keyword, it doesn't expand the tab group and auto-scroll to the active tab.

The setting is enabled and it does work sometimes, depending on the situation.

I think it would be great if in the side panel, we can have a button that you can click on to force auto-scroll to active tab.

**Comment by ymlluo** [comment]
We've tested this and confirmed it's a bug. We'll fix it in the next version.
Also, if the active tab is no longer visible, an icon will appear in the top toolbar. 

<img width="543" height="87" alt="Image" src="https://github.com/user-attachments/assets/654f10e7-7515-485f-94ca-e51848aae11f" />

Click it to scroll back to the active tab.
Thanks for your feedback.

**Comment by chaoscreater** [comment]
Another note, if I switch between Active Tabs and All Tabs, it should auto-scroll to the correct position in the sidebar.

**Comment by ymlluo** [comment]
Thank you for your feedback. We've noticed this issue and will fix it in the next version. Due to ongoing major feature development, the new release is still pending and will take some more time.

**Comment by ymlluo** [comment]
We have released a new version 3.4.0 that optimizes this issue. You can try it to see if it resolves the problem.

**Comment by chaoscreater** [comment]
@ymlluo 

Hi there,

Happy New Year. I've just updated to the latest January 2026 version and the scroll to activate tab is still not working properly. If I click Active Tabs panel and then click back to All Tabs panel, it doesn't scroll to the active tab. 

Also, if I search for a keyword and click on tab ABC, then I remove the search, it should auto-scroll to the tab in the tree view, but it doesn't.
